### ISSUE TITLE
'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by dbonomo** [pitchmuc/audiencemanager#1]
Hi folks, very excited to get started with this library.

Sorry if this is the wrong location to ask this, but I've run into an issue

I've gone through the get-started.md document (https://github.com/pitchmuc/audiencemanager/blob/master/docs/get-started.md) and followed steps 1-4. When I try to define myCompany = aam.AudienceManager(), I get the error `'str' object has no attribute 'decode'`.

Could you please let me know if I missed a step along the way or need to do something differently?
![image](https://user-images.githubusercontent.com/320331/148139404-c49022a5-5f89-41b1-9f89-bc50fc0b757f.png)

**Comment by pitchmuc** [comment]
Hello @dbonomo 
Sorry for the late reply, I was on vacation.
I think that I know what the issue is, you have the latest version of pyJWT
Do you know which version do you use ? 
I will upload a new version that supports the latest version of pyJWT (and revamp a bit the module)

**Comment by pitchmuc** [comment]
The new version is live, you can download via this command: 
`pip install audiencemanager --upgrade`
Let me know if this fix your issue. 

Best,

**Comment by dbonomo** [comment]
Thank you Julien!

The update removed the error me. I really appreciate it.

Cheers,

-Dan

**Comment by dbonomo** [comment]
Oh and for the record, I am using jwt version '2.3.0'.

**Comment by pitchmuc** [comment]
Thanks for confirming, the previous script was supporting jwt below 2.0.0.
Now you are good to go. 
Have fun
